// scripts/seed.ts
// Run with: npx tsx scripts/seed.ts
// Seeds pg_properties table with real Gharpayy PG data

/* eslint-disable @typescript-eslint/no-require-imports */
const { createClient } = require("@supabase/supabase-js");
const fs = require("fs");
const path = require("path");

// Load .env.local manually without dotenv
function loadEnv() {
  const envPath = path.join(process.cwd(), ".env.local");
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const [key, ...rest] = trimmed.split("=");
    if (key && rest.length) process.env[key.trim()] = rest.join("=").trim();
  }
}
loadEnv();

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const COMMON_AMENITIES = [
  "Wifi", "Laundry Area", "Power Backup", "Elevator",
  "Water Purifier", "Fridge", "Microwave", "Housekeeping",
];
const COMMON_SAFETY = ["CCTV", "Security Guard", "Fire Extinguisher"];
const COMMON_COMMON = ["Lounge", "Gym", "Pantry", "Rooftop"];

const pgs = [
  {
    gharpayy_name: "FORUM PRO BOYS",
    area: "Koramangala",
    locality: "Silk Board, SG Palaya",
    nearby_landmarks: "Nexus Mall, Christ University, Dairy Circle, Koramangala 5th/6th Block",
    google_maps_url: "https://maps.app.goo.gl/CDmFo9KYX3Ds7anv7",
    gender: "Boys",
    target_audience: "Both",
    property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Fully Furnished with all amenities",
    walking_distance_mins: "10",
    accessibility: "Bus",
    noise_level: "Medium",
    surrounding_vibe: "Vibe Is very good, All good restaurants are nearby",
    food_type: "Veg",
    common_area_features: [...COMMON_COMMON, "Study Area"],
    amenities: COMMON_AMENITIES,
    safety_features: COMMON_SAFETY,
    meals_per_day: 4,
    food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive (Electricity + Water + Wi-Fi + Maintenance)",
    cleaning_frequency: "Every Alternate Day",
    usp: "Newly built, GYM, GAMES, No Curfew",
    house_rules: "No Curfew",
    security_deposit: "One Month Rent",
    minimum_stay: "3 Months",
    price_triple: 13000, price_double: 16000, price_single: 23000,
    manager_contact: "8296124422",
    group_name: "Kalpavriksha", actual_name: "KLP",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "FORUM 1 BOYS",
    area: "Koramangala", locality: "Silk Board, SG Palaya",
    nearby_landmarks: "Nexus Mall, Christ University, Dairy Circle",
    google_maps_url: "https://maps.app.goo.gl/CDmFo9KYX3Ds7anv7",
    gender: "Boys", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Fully Furnished", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Vibe Is very good, All good restaurants are nearby",
    food_type: "Veg", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 4, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Newly built, GYM, GAMES, No Curfew", house_rules: "No Curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 12000, price_double: 15000, price_single: 24000,
    manager_contact: "7275630428", group_name: "Kalpavriksha", actual_name: "KLP",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "AIRA BOYS",
    area: "Koramangala", locality: "SG Palaya, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, Dairy Circle",
    google_maps_url: "https://maps.app.goo.gl/FYuooqoSNE6uyZVQ7",
    gender: "Boys", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Veg", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 4, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Newly built, GYM, GAMES, No curfew", house_rules: "No curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 15000, price_single: 24000,
    manager_contact: "9731750056", actual_name: "AIRAVATI PG",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "WINK BOYS",
    area: "Koramangala", locality: "Adugodi, Tavrekere",
    nearby_landmarks: "Nexus Mall, Christ University, Fiserv, Accenture, Razorpay",
    google_maps_url: "https://maps.app.goo.gl/mzDvnmaU4jSv9uws6",
    gender: "Boys", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "All restaurants nearby, good nightlife",
    food_type: "Veg", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 4, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "GYM, GAMES, Very nearby to Christ, Fiserv, Accenture, Razorpay",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 12000, price_single: 19000,
    owner_contact: "9514130240", actual_name: "Purple BOYS PG",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "ZEXUS BOYS",
    area: "Koramangala", locality: "SG Palya, Tavrekere, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, Fiserv, Accenture, Razorpay",
    google_maps_url: "https://maps.app.goo.gl/MXaGBkoENA3icm6r7",
    gender: "Boys", target_audience: "Both", property_type: "Premium",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "2",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "All restaurants nearby, good nightlife",
    food_type: "Veg", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "Electricity Bill Extra (AC is 2K extra)",
    cleaning_frequency: "Every Alternate Day",
    usp: "Premium property, GYM, GAMES, 2 min from landmark",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 16000, price_single: 27000,
    manager_contact: "8882037105", manager_name: "Janaki Thappa",
    owner_contact: "9844027607", owner_name: "Mahesh",
    group_name: "Gharpayy x Zexus Boys", actual_name: "Your Space",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "NEX COED",
    area: "Koramangala", locality: "SG Palya, Nexus, Tavrekere",
    nearby_landmarks: "Nexus Mall, Christ University, Fiserv, Accenture, Razorpay",
    google_maps_url: "https://maps.app.goo.gl/FYuooqoSNE6uyZVQ7",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "All restaurants nearby, good nightlife",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "Electricity Bill Extra", cleaning_frequency: "Every Alternate Day",
    usp: "GAMES, Very nearby to Christ, Fiserv, Accenture, Razorpay",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 13000, price_double: 17000, price_single: 27000,
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "ROAR COED",
    area: "Koramangala", locality: "SG Palya, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, IBC Knowledge Park, Dairy Circle",
    google_maps_url: "https://maps.app.goo.gl/FYuooqoSNE6uyZVQ7",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Vibe Is very good, All good restaurants are nearby",
    food_type: "Veg", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 4, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Coliving stay - rarely available, best & big rooms, great food",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 13000, price_single: 23000,
    manager_name: "Ram", manager_contact: "9721538096",
    owner_name: "Ramesh", owner_contact: "9600530780",
    actual_name: "SLV Luxury Coliving PG",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "GRAND GIRLY",
    area: "Koramangala", locality: "SG Palya, Tavrekere, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, Fiserv, Accenture, Razorpay",
    google_maps_url: null,
    gender: "Girls", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "All restaurants nearby, good nightlife",
    food_type: "Veg", common_area_features: ["Lounge", "Pantry", "Rooftop"],
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "GAMES, Very nearby to Christ, Fiserv, Accenture, Razorpay",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 12000, price_double: 14000, price_single: 25000,
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "S GIRLY RK",
    area: "Koramangala", locality: "SG Palya, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, Fiserv, Accenture, Razorpay",
    google_maps_url: "https://maps.app.goo.gl/y6Rf5dBpvY6TBak3A",
    gender: "Girls", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "All restaurants nearby, good nightlife",
    food_type: "Veg", common_area_features: [...COMMON_COMMON, "Study Area"],
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "GAMES, Very nearby to Christ, Fiserv, Accenture, Razorpay",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 14000, price_single: 27000,
    owner_contact: "8105580674", actual_name: "SRI PMR PG FOR LADIES",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "JOY GIRLS",
    area: "Koramangala", locality: "Silk Board, SG Palaya, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, Dairy Circle",
    google_maps_url: "https://maps.app.goo.gl/D2rG63LzrV9a7X1N9",
    gender: "Girls", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "All restaurants nearby, good nightlife",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Newest PG, Prime Location, WFH Enabler, Food Good, No curfew",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 12000, price_double: 15000, price_single: 24000,
    manager_name: "Govind", manager_contact: "7353735588",
    owner_contact: "9110592795", actual_name: "Siri Paradise",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "GT GIRLS",
    area: "Koramangala", locality: "Silk Board, SG Palaya, MG Road, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, IBC Knowledge Park, Dairy Circle",
    google_maps_url: "https://maps.app.goo.gl/aCdXQorPaPbkstsc6",
    gender: "Girls", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chats", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Low",
    surrounding_vibe: "Very good vibe, all restaurants near",
    food_type: "Veg", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 4, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Newly built, GYM, GAMES, BEST GIRLS PROPERTY IN KORAMANGALA",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 15000, price_single: 24000,
    actual_name: "My Roomie Lavender",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "HOMY GIRLS",
    area: "Koramangala", locality: "Silk Board, SG Palaya, Nexus",
    nearby_landmarks: "Nexus Mall, Christ University, Dairy Circle",
    google_maps_url: "https://maps.app.goo.gl/cokeKf8enryASuxP9",
    gender: "Girls", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Fully Furnished", walking_distance_mins: "15",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Nearby to Christ, Fiserv, Accenture, Razorpay",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 4, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Newly built, GYM, GAMES", house_rules: "No Curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 19000, price_single: 28000,
    manager_name: "Safan", manager_contact: "6363722172",
    owner_name: "Safan", owner_contact: "6363722172", actual_name: "Nook Astella",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "CIA COED",
    area: "Nagawara", locality: "Manyata, Hebbal Circle",
    nearby_landmarks: "Manyata Tech Park",
    google_maps_url: "https://maps.app.goo.gl/rgAoSF42L1NFdeGp7",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: [...COMMON_COMMON, "Parking"],
    amenities: COMMON_AMENITIES,
    safety_features: ["CCTV", "Security Guard", "Biometric Access", "Fire Extinguisher"],
    meals_per_day: 2, food_timings: "Breakfast 6:30-9:30am | Dinner 7:30-9:30pm (weekdays)",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Good PG, Prime Location, WFH Enabler, Food Good, No curfew",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 13000, price_single: 22000,
    manager_name: "Rajendra", manager_contact: "7022568295",
    owner_name: "Madan Reddy", owner_contact: "9916669290",
    group_name: "Gopu x Gharpayy", actual_name: "MG Gopu Homestays G4",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "MAGNUS COED",
    area: "Nagawara", locality: "Manyata, Hebbal Circle",
    nearby_landmarks: "Manyata Tech Park",
    google_maps_url: "https://maps.app.goo.gl/wVcQBggkCpdj2cMB7",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: ["Lounge", "Gym", "Study Area", "Rooftop"],
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "New Property, No curfew", house_rules: "No curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 11000, price_double: 13000, price_single: 17000,
    owner_name: "Ranga Reddy", owner_contact: "7997477685",
    group_name: "Surya Colive x Gharpayy", actual_name: "Surya Coliving PG - Magnus",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "KNOX COED",
    area: "Bellandur", locality: "Kadubeesanahalli",
    nearby_landmarks: "Sony Software India, Embassy Tech Village",
    google_maps_url: "https://maps.app.goo.gl/adWbc5Z28ixXXGyr7",
    gender: "Co-live", target_audience: "Both", property_type: "Budget",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "5",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: [...COMMON_COMMON, "Study Area"],
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Extremely budget friendly, mini gym & games, No curfew",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 13000, price_single: 23000,
    manager_contact: "7337777916",
    group_name: "IVA COLIVING x Gharpayy", actual_name: "IVA COLIVING",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "BELL COED",
    area: "Bellandur", locality: "Bellandur",
    nearby_landmarks: "Ecoworld, Flipkart",
    google_maps_url: "https://maps.app.goo.gl/GcoEbrkPuJVseYCC8",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "40",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Peak Location, Newly Built with Love, Pocket Friendly",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 11000, price_double: 13000, price_single: 21000,
    manager_name: "Manoj", manager_contact: "9110664880",
    owner_name: "Mansa", owner_contact: "9108895879",
    actual_name: "Adler Bellandur",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "ZILLION COED",
    area: "Bellandur", locality: "Ecoworld, Bellandur, Flipkart",
    nearby_landmarks: "Ecoworld, Flipkart",
    google_maps_url: "https://maps.app.goo.gl/vqxjy8YQzH9H9DAZA",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "40",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Newest PG, Prime Location, WFH Enabler, Food Good, No Curfew",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 15000, price_single: 25000,
    manager_contact: "7996679991", owner_contact: "9739997392",
    actual_name: "FAB INN by Echo Coliving",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "ZEAL COED",
    area: "Mahadevapura", locality: "Bagmane, CV Raman",
    nearby_landmarks: "EY, Coral Building, Bagmane World Technology Center",
    google_maps_url: "https://maps.app.goo.gl/gvTbqnKKAzXNHt969",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "30",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Extremely budget friendly, mini gym & games",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 12000, price_single: 22000,
    owner_contact: "7829930666", group_name: "Bliss Group", actual_name: "Blis Comfort",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "MIVON COED",
    area: "Mahadevapura", locality: "Bagmane, CV Raman",
    nearby_landmarks: "EY, Coral Building, Bagmane World Technology Center",
    google_maps_url: "https://maps.app.goo.gl/A2gTtGAhC4GfLByK9",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Double Sharing Suite"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "15",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Extremely budget friendly, mini gym & games",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 16000, price_single: 28000,
    manager_name: "Mahesh", manager_contact: "7729858699",
    group_name: "Urban Coliving x Gharpayy", actual_name: "Urban Coliving",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "MYSTIC COED",
    area: "Marathahalli", locality: "AECS Layout",
    nearby_landmarks: "Marathahalli Market",
    google_maps_url: "https://maps.app.goo.gl/EydKS2YoehU6uhfm7",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "40",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Budget friendly, games", house_rules: "No Curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 13000, price_single: 24000,
    manager_name: "Srinu", manager_contact: "8500931018",
    group_name: "Orion Living x Gharpayy", actual_name: "Flux Coliving",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "BIGBROOK",
    area: "Mahadevapura", locality: "Brookfield, Bagmane, CV Raman",
    nearby_landmarks: "EY, Coral Building, Bagmane World Technology Center",
    google_maps_url: "https://maps.app.goo.gl/1JSY7tnYhzS6TxtU9",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: [...COMMON_COMMON, "Parking"],
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Budget friendly, games", house_rules: "No Curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 17000, price_single: 30000,
    group_name: "Apex Coliving", actual_name: "Apex Coliving",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "FLEX COED",
    area: "Electronic City", locality: "Shanthipura, Electronic City",
    nearby_landmarks: "Semicon Park, Tech37",
    google_maps_url: "https://maps.app.goo.gl/oQYZPJRAYMoQwhp29",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "15",
    accessibility: "Metro, Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES,
    safety_features: ["CCTV", "Security Guard", "Biometric Access", "Fire Extinguisher"],
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Games, Very nearby to offices", house_rules: "No curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 9000, price_double: 11000, price_single: 17000,
    owner_name: "Indrasena", owner_contact: "9515775563",
    group_name: "P2 Liv In x Gharpayy", actual_name: "E-City Phase 2 Live In Space",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "POP COED",
    area: "Electronic City", locality: "Electronic City",
    nearby_landmarks: "Tech37, Infosys",
    google_maps_url: "https://maps.app.goo.gl/pwusitauxJDy9NfXA",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "15",
    accessibility: "Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Games, Very nearby to offices", house_rules: "No curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 10000, price_single: 16000,
    owner_contact: "9989285854",
    group_name: "Gharpayy x POP COED", actual_name: "Leo PG",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "METROFIELD COED",
    area: "Whitefield", locality: "Hopefarm, ITPL, Whitefield",
    nearby_landmarks: "ITPL",
    google_maps_url: "https://maps.app.goo.gl/mg2SiKg9ZeoND79v6",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Metro, Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Flat type setup, 2W parking, Best metro connectivity",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 15000, price_single: 24000,
    manager_contact: "9008122779", actual_name: "Hektor",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "WHIT COED",
    area: "Whitefield", locality: "Hopefarm, ITPL, Whitefield",
    nearby_landmarks: "ITPL",
    google_maps_url: "https://maps.app.goo.gl/gWyt5JCjXRZed4WY6",
    gender: "Co-live", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "10",
    accessibility: "Metro, Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Balcony room, budget stay, food included",
    house_rules: "No curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: null, price_double: 9000, price_single: 17000,
    manager_name: "Sravya", manager_contact: "8639653441",
    owner_name: "Sravya", owner_contact: "8639653441",
    actual_name: "Oka Colive",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "LUNA GIRLS",
    area: "Jayanagar", locality: "Jayanagar",
    nearby_landmarks: "Jayanagar",
    google_maps_url: "https://maps.app.goo.gl/x7frvw1knt4JgM4y9",
    gender: "Girls", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "5",
    accessibility: "Metro", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Great property, GAMES, Very nearby to offices",
    house_rules: "No Curfew", security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 16000, price_double: 19000, price_single: 31000,
    manager_name: "Vinod", manager_contact: "7416687752",
    owner_name: "Vishnu Reddy", owner_contact: "7411911136",
    actual_name: "Ladies PG Jayanagar",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "VELVET GIRLS",
    area: "MG Road", locality: "MG Road, Vasanth Nagar",
    nearby_landmarks: "MG Road",
    google_maps_url: "https://maps.app.goo.gl/ad1JHPLHtfBxF2Q78",
    gender: "Girls", target_audience: "Both", property_type: "Mid",
    room_types: ["Single Sharing", "Double Sharing", "Triple Sharing"],
    furnishing_details: "Amenities as per chat", walking_distance_mins: "5",
    accessibility: "Metro, Bus", noise_level: "Medium",
    surrounding_vibe: "Working professional and posh crowd",
    food_type: "Both", common_area_features: COMMON_COMMON,
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Budget friendly, games", house_rules: "No curfew",
    security_deposit: "One Month Rent", minimum_stay: "3 Months",
    price_triple: 10000, price_double: 14000, price_single: 24000,
    owner_contact: "8088303270", actual_name: "Hive Living",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "HS METRO COED",
    area: "HSR Layout", locality: "HSR Layout",
    nearby_landmarks: "HSR Layout Metro Station, Bommanahalli Metro",
    google_maps_url: "https://maps.app.goo.gl/x5b7KqMMoRACS369A",
    gender: "Co-live", target_audience: "Both", property_type: "Premium",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Fully Furnished", walking_distance_mins: "3",
    accessibility: "Metro, Bus, Bike", noise_level: "Medium",
    surrounding_vibe: "Premium locality",
    food_type: "Both", common_area_features: [...COMMON_COMMON, "Parking"],
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "3 times Veg/Non-Veg daily",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Metro connectivity, Premium location", house_rules: "Read T&C",
    security_deposit: "Read T&C", minimum_stay: "3 Months",
    price_triple: null, price_double: 15000, price_single: 25000,
    manager_contact: "7899700929", actual_name: "Sivani Co Living",
    is_approved: true, is_available: true,
  },
  {
    gharpayy_name: "HS HUGO COED",
    area: "HSR Layout", locality: "HSR Layout, near Hogasandra metro",
    nearby_landmarks: "Hogasandra Metro Station",
    google_maps_url: "https://maps.app.goo.gl/52tJEDzbfbMvTDLF7",
    gender: "Co-live", target_audience: "Both", property_type: "Premium",
    room_types: ["Single Sharing", "Double Sharing"],
    furnishing_details: "Fully Furnished", walking_distance_mins: "3",
    accessibility: "Metro, Bus, Bike", noise_level: "Low",
    surrounding_vibe: "Good Locality",
    food_type: "Both", common_area_features: ["Lounge", "Pantry", "Study Area", "Rooftop"],
    amenities: COMMON_AMENITIES, safety_features: COMMON_SAFETY,
    meals_per_day: 3, food_timings: "Read T&C",
    utilities_included: "All Inclusive", cleaning_frequency: "Every Alternate Day",
    usp: "Cherry blossom, Premium location", house_rules: "Read T&C",
    security_deposit: "Read T&C", minimum_stay: "3 Months",
    price_triple: null, price_double: 15000, price_single: 25000,
    manager_contact: "7899700929", actual_name: "Cherry Blossom",
    is_approved: true, is_available: true,
  },
];

async function seed() {
  console.log("🌱 Seeding pg_properties...");
  const { error: delErr } = await supabase
    .from("pg_properties")
    .delete()
    .neq("id", "00000000-0000-0000-0000-000000000000");
  if (delErr) console.warn("Delete warning:", delErr.message);

  const { data, error } = await supabase.from("pg_properties").insert(pgs).select();
  if (error) { console.error("❌ Seed error:", error.message); process.exit(1); }
  console.log(`✅ Seeded ${data?.length} PG properties successfully!`);
  const areas = [...new Set(pgs.map((p) => p.area))];
  console.log("Areas covered:", areas.join(", "));
}

seed();
