// scripts/seed.ts — Full Gharpayy PG seed from IQ + FIND_PG_DATA sheets
// Run: npx tsx scripts/seed.ts

/* eslint-disable @typescript-eslint/no-require-imports */
const { createClient } = require("@supabase/supabase-js");
const fs   = require("fs");
const path = require("path");

function loadEnv() {
  const envPath = path.join(process.cwd(), ".env.local");
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, "utf-8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const [k, ...v] = t.split("=");
    if (k && v.length) process.env[k.trim()] = v.join("=").trim();
  }
}
loadEnv();

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

// ─── Shared defaults ───────────────────────────────────────────────────────
const AMN  = ["Wifi","Laundry Area","Power Backup","Elevator","Water Purifier","Fridge","Microwave","Housekeeping"];
const AMN_PARKING = [...AMN, "Parking"];
const SAF  = ["CCTV","Security Guard","Fire Extinguisher"];
const SAF_BIO = [...SAF, "Biometric Access"];
const COM  = ["Lounge","Gym","Pantry","Rooftop"];
const COM_STUDY = [...COM, "Study Area"];
const std  = { target_audience:"Both", furnishing_details:"Fully Furnished", accessibility:"Bus",
               noise_level:"Medium", utilities_included:"All Inclusive (Electricity + Water + Wi-Fi + Maintenance)",
               cleaning_frequency:"Every Alternate Day", security_deposit:"One Month Rent",
               minimum_stay:"3 Months", is_approved:true, is_available:true,
               house_rules:"No Curfew" };
const food3 = { meals_per_day:3, food_timings:"Breakfast 6:30-9:30am | Lunch 12:30-3pm | Dinner 7:30-9:30pm" };
const food4 = { meals_per_day:4, food_timings:"Breakfast 6:30-9:30am | Lunch 12:30-3pm | Snacks 5-6pm | Dinner 7:30-9:30pm" };
const food2 = { meals_per_day:2, food_timings:"Breakfast 6:30-9:30am | Dinner 7:30-9:30pm (weekdays)" };
const NL = "Nexus Mall, Christ University, Dairy Circle, Koramangala 5th/6th Block";
const MTP = "Manyata Tech Park, Hebbal";
const ECV = "Bagmane World Technology Center, EY, Coral Building";
const WF  = "ITPL, Hopefarm, Whitefield";
const BL  = "Ecoworld, Bellandur, Flipkart";
const MR  = "Marathahalli Market, AECS";

const pgs: any[] = [

  // ─── KORAMANGALA ────────────────────────────────────────────────────────
  { gharpayy_name:"FORUM PRO BOYS",  area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/CDmFo9KYX3Ds7anv7", gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Great vibe, restaurants and nightlife nearby", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Newly built, GYM, GAMES, 4 meals/day", price_triple:13000, price_double:16000, price_single:23000,
    manager_contact:"8296124422", group_name:"Kalpavriksha", actual_name:"KLP", ...std },

  { gharpayy_name:"FORUM 1 BOYS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/CDmFo9KYX3Ds7anv7", gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Great vibe, restaurants and nightlife nearby", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Newly built, GYM, GAMES, No Curfew", price_triple:12000, price_double:15000, price_single:24000,
    manager_contact:"7275630428", group_name:"Kalpavriksha", actual_name:"KLP", ...std },

  { gharpayy_name:"AIRA BOYS", area:"Koramangala", locality:"SG Palaya, Tavrekere", nearby_landmarks:NL,
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Newly built, GYM, GAMES, No curfew", price_double:15000, price_single:24000,
    manager_contact:"9731750056", ...std },

  { gharpayy_name:"WINK BOYS", area:"Koramangala", locality:"Adugodi, Tavrekere", nearby_landmarks:NL,
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"GYM, GAMES, very close to Christ, Fiserv, Accenture, Razorpay",
    price_double:12000, price_single:19000,
    owner_contact:"9514130240", ...std },

  { gharpayy_name:"ZEXUS BOYS", area:"Koramangala", locality:"SG Palaya, Tavrekere", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/MXaGBkoENA3icm6r7",
    gender:"Boys", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"2 min from landmark, GYM, GAMES, premium property",
    price_double:16000, price_single:27000,
    manager_contact:"8882037105", owner_contact:"9844027607", group_name:"Gharpayy x Zexus", ...std },

  { gharpayy_name:"GRAND GIRLY", area:"Koramangala", locality:"SG Palaya, Tavrekere", nearby_landmarks:NL,
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Veg",
    common_area_features:["Lounge","Pantry","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"GAMES, close to Christ, Fiserv, Accenture", price_triple:12000, price_double:14000, price_single:25000,
    ...std },

  { gharpayy_name:"S GIRLY RK", area:"Koramangala", locality:"SG Palaya, Tavrekere", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/y6Rf5dBpvY6TBak3A",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"GAMES, close to Christ, Fiserv, Accenture",
    price_double:14000, price_single:27000,
    owner_contact:"8105580674", group_name:"GG Affordable SG", actual_name:"Sri PMR PG for Ladies", ...std },

  { gharpayy_name:"NEX COED", area:"Koramangala", locality:"SG Palaya, Tavrekere", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/FYuooqoSNE6uyZVQ7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    utilities_included:"ELECTRICITY BILL EXTRA",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"GAMES, close to Christ, Fiserv, Accenture",
    price_triple:13000, price_double:17000, price_single:27000,
    ...std },

  { gharpayy_name:"JOY GIRLS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/D2rG63LzrV9a7X1N9",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_triple:12000, price_double:15000, price_single:24000,
    manager_contact:"7353735588", owner_contact:"9110592795", actual_name:"Siri Paradise", ...std },

  { gharpayy_name:"WYSE GIRLS", area:"Koramangala", locality:"IBC Knowledge Park, Christ Central", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/NJqLFowfyQBx4San9",
    gender:"Girls", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Flat setup, no curfew", price_double:19000, price_single:31000,
    ...std },

  { gharpayy_name:"XOLD FLAT LIKE", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/iFrPomz1xsdUjkGP9",
    gender:"Co-live", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Flat type setup with sofa, fridge, TV, 2W parking, daily cleaning",
    price_triple:11000, price_double:15000, price_single:24000,
    manager_contact:"9870227819", actual_name:"Stellar House", ...std },

  { gharpayy_name:"ROAR COLIVE", area:"Koramangala", locality:"IBC Knowledge Park", nearby_landmarks:NL,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Great vibe, all good restaurants nearby", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Coliving stay – rarely available, best & big rooms, great food",
    price_double:13000, price_single:23000,
    manager_contact:"9721538096", owner_contact:"9600530780", actual_name:"SLV Luxury Coliving PG", ...std },

  { gharpayy_name:"SG COLIVE", area:"Koramangala", locality:"IBC Knowledge Park, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/NJqLFowfyQBx4San9",
    gender:"Co-live", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_triple:9000, price_double:13000, price_single:23000,
    manager_contact:"6205229187", owner_contact:"7598844465", actual_name:"Nesto Amigo SG", ...std },

  { gharpayy_name:"ORANGE CAPITAL", area:"Koramangala", locality:"Hosur Road, Adugodi", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/MXaGBkoENA3icm6r7",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Great vibe, all good restaurants nearby", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Prime location, big rooms, good food",
    price_double:13000, price_single:20000,
    manager_contact:"8050509559", actual_name:"Adler near Pink Cap", ...std },

  { gharpayy_name:"FAB GIRLS", area:"Koramangala", locality:"Hosur Road, Adugodi", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/ocG1LjwkSpT17z1i8",
    gender:"Girls", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Great vibe, all good restaurants nearby", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"400m from Christ Central back gate",
    price_triple:10000, price_double:13000, price_single:23000,
    manager_contact:"8296728581", actual_name:"Adler near Ace", ...std },

  { gharpayy_name:"GT GIRLS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/aCdXQorPaPbkstsc6",
    gender:"Girls", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Very good vibe, all restaurants near", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Best girls property in Koramangala, GYM, GAMES",
    price_double:15000, price_single:24000,
    actual_name:"My Roomie Lavender", ...std },

  { gharpayy_name:"ELITE COED", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Great vibe, restaurants nearby", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_triple:12000, price_double:15000, price_single:23000,
    manager_contact:"8217411288", actual_name:"Kalpavriksha 5 New", ...std },

  { gharpayy_name:"BYG COED", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/iFrPomz1xsdUjkGP9",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Great vibe, restaurants nearby", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_double:13000, price_single:25000,
    manager_contact:"7337433078", actual_name:"Siva Malleswari Coliving", ...std },

  { gharpayy_name:"TAVZ COED", area:"Koramangala", locality:"Tavrekere", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/3kV2t1AHyoTL9yTv7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Affordable coliving, no curfew", price_double:10000, price_single:17000,
    manager_contact:"7353735588", actual_name:"Royal Paradise 1", ...std },

  { gharpayy_name:"JAZZ COED", area:"Koramangala", locality:"SG Palaya, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/MXaGBkoENA3icm6r7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Great vibe, all restaurants nearby", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food4,
    usp:"4 meals/day, prime location",
    price_double:16000, price_single:29000,
    actual_name:"Atlas Coliving PG", ...std },

  { gharpayy_name:"SNOOK COED", area:"Koramangala", locality:"IBC Knowledge Park, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/vE8zuuooe9tDMvo66",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Great vibe, all restaurants nearby", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Budget friendly, gym & games",
    price_triple:12000, price_double:14000, price_single:23000,
    manager_contact:"8310877020", owner_contact:"9487626144", actual_name:"Yes Living", ...std },

  { gharpayy_name:"HOMY GIRLS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/cokeKf8enryASuxP9",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Close to Christ, Fiserv, Accenture, Razorpay", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"GYM, GAMES, prime location",
    price_double:19000, price_single:28000,
    manager_contact:"6363722172", actual_name:"Nook Astella", ...std },

  { gharpayy_name:"TOM BOYS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/D2rG63LzrV9a7X1N9",
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Best PG food, gym, super close to everything",
    price_triple:12000, price_double:15000, price_single:23000,
    manager_contact:"7204036862", group_name:"KLP", actual_name:"Kalpavriksha", ...std },

  { gharpayy_name:"HOMELY BOYS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/FYuooqoSNE6uyZVQ7",
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"GYM, GAMES, newly built",
    price_triple:14000, price_double:17000, price_single:24000,
    manager_contact:"6364800803", group_name:"KLP", actual_name:"Kalpavriksha", ...std },

  { gharpayy_name:"HOMELY GIRLS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/FYuooqoSNE6uyZVQ7",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food4,
    usp:"GYM, GAMES, newly built",
    price_triple:14000, price_double:17000, price_single:24000,
    manager_contact:"6364800803", group_name:"KLP 1 Girls", actual_name:"Kalpavriksha", ...std },

  { gharpayy_name:"GQ GIRLS", area:"Koramangala", locality:"IBC Knowledge Park, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/cokeKf8enryASuxP9",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Super close to everything, good PG food, next to mall",
    price_double:17000, price_single:25000,
    manager_contact:"8884449621", actual_name:"My Home Grandeur", ...std },

  { gharpayy_name:"ESPLANADE GIRLS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/aCdXQorPaPbkstsc6",
    gender:"Girls", property_type:"Budget",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Best girls property in Koramangala, GYM, GAMES",
    price_triple:21000, price_double:24000, price_single:37000,
    manager_contact:"6364800803", actual_name:"Kalpavriksha Gardenia", ...std },

  { gharpayy_name:"AFFO GIRLS NV", area:"Koramangala", locality:"IBC Knowledge Park, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/4h5a93JbPuD5ezUs7",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Non-veg available, super close to everything, good food",
    price_double:12500, price_single:22000,
    manager_contact:"9032867594", owner_contact:"7892014576",
    group_name:"GG Madhavi Homes CL Layout", actual_name:"Class House", ...std },

  { gharpayy_name:"PINK CAPITAL", area:"Koramangala", locality:"Hosur Road", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/MXaGBkoENA3icm6r7",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Pink & new interiors, prime location",
    price_double:13000, price_single:18000,
    manager_contact:"9611728757", owner_contact:"7892131987", actual_name:"73 House of Zisk", ...std },

  { gharpayy_name:"KHB GIRLS", area:"Koramangala", locality:"8th Block, Koramangala", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/XTQKRKuvCX2C54xP9",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Peak location, newly built with love, pocket friendly",
    price_triple:11000, price_double:13000, price_single:24000,
    manager_contact:"9160689366", group_name:"Nirvana", actual_name:"Nirvana", ...std },

  { gharpayy_name:"KHB BOYS", area:"Koramangala", locality:"SG Palaya", nearby_landmarks:NL,
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, good location",
    price_triple:10000, price_double:14000, price_single:21000,
    manager_contact:"8999972220", owner_contact:"9160689366", actual_name:"Sri Varahi", ...std },

  { gharpayy_name:"JOHN BOYS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/Mukfn9vnVK9vN8up8",
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_triple:9000, price_double:12000, price_single:19000,
    manager_contact:"9440002382", owner_contact:"8374243567", actual_name:"RR PG", ...std },

  { gharpayy_name:"JACK COED", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/iFrPomz1xsdUjkGP9",
    gender:"Co-live", property_type:"Mid",
    room_types:["Double Sharing","Triple Sharing"],
    surrounding_vibe:"Great vibe, all restaurants nearby", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Snooker, chess, carrom, wakefit mattress, big almirahs",
    price_triple:15000, price_double:18000,
    manager_contact:"8951598703", actual_name:"Euphoria", ...std },

  { gharpayy_name:"G FORUM GIRLS", area:"Koramangala", locality:"IBC Knowledge Park, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/rSsdLXmWjA3CwbES7",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Super close to everything, good PG food, next to mall",
    price_double:14000, price_single:22000,
    manager_contact:"8800887053", owner_contact:"9606631307", actual_name:"Class House", ...std },

  { gharpayy_name:"ACE GIRLS", area:"Koramangala", locality:"Madiwala, SG Palaya, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://g.co/kgs/P2Y3STi",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Great vibe, all restaurants nearby", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food4,
    usp:"Super big almirahs, Wakefit mattresses, snooker, chess, carrom",
    price_double:23000, price_single:27000,
    manager_contact:"7619210662", owner_contact:"9606333530", actual_name:"Puzzles Living Grandeur House", ...std },

  { gharpayy_name:"QUIN GIRLS", area:"Koramangala", locality:"IBC Knowledge Park, Dairy Circle", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/cokeKf8enryASuxP9",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Great vibe, all restaurants nearby", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food4,
    usp:"Super close to everything, next to mall",
    price_double:15000, price_single:25000,
    actual_name:"Class House", ...std },

  { gharpayy_name:"KORAVILL GIRLS", area:"Koramangala", locality:"Ejipura", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/SFHBbpj2hKuKBLCQA",
    gender:"Girls", property_type:"Budget", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby", food_type:"Both",
    common_area_features:["Lounge","Study Area","Rooftop"], amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"Budget friendly, 2 min from landmark",
    price_triple:11000, price_double:13000, price_single:22000,
    manager_contact:"8310714410", actual_name:"Monika Ladies PG",
    walking_distance_mins:"2", ...std },

  { gharpayy_name:"KORVE COED", area:"Koramangala", locality:"Koramangala", nearby_landmarks:NL,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area, surrounded", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF,
    meals_per_day:2, food_timings:"Weekdays: Breakfast & Dinner",
    usp:"Premium property", price_double:22000, price_single:35000,
    manager_contact:"8139991234", owner_contact:"9701848769", actual_name:"Nextt Door",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"ZEXX COED", area:"Koramangala", locality:"SG Palaya", nearby_landmarks:NL,
    gender:"Co-live", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good friendly vibe", food_type:"Veg",
    common_area_features:["Lounge","Gym"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly property",
    price_double:13000, price_single:20000,
    manager_contact:"8867972551", owner_contact:"8951142499", actual_name:"Mojo Princeton",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"QUT GIRLS", area:"Koramangala", locality:"SG Palaya", nearby_landmarks:NL,
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Surrounded with restaurants", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly rooms", price_triple:11000, price_double:13000, price_single:20000,
    manager_contact:"8792915685", owner_contact:"8951142499", actual_name:"Mojo Harward House",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"TOVE BOYS", area:"Koramangala", locality:"SG Palaya", nearby_landmarks:NL,
    gender:"Boys", property_type:"Budget",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Friendly area", food_type:"Veg",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly property",
    price_triple:8000, price_double:12000, price_single:18000,
    manager_contact:"7294828337", owner_contact:"8884123459", actual_name:"Sapthagiri PG",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"MVS PEARLS", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/ZabqhMQqxJ9oDNo8A",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Great vibe, all restaurants nearby", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"Premium flat-like setup",
    price_double:15000, price_single:23000,
    manager_contact:"7022914317", owner_contact:"9535200009", actual_name:"DC Gardenia", ...std },

  { gharpayy_name:"GG BUBBLO GIRLS", area:"Koramangala", locality:"SG Palaya, Tavrekere", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/Rdo9UCsirJ3ZcPRKA",
    gender:"Girls", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby, good nightlife", food_type:"Both",
    common_area_features:COM, amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"Budget friendly, gym & games",
    price_double:13000, price_single:21000,
    actual_name:"Gayathri PG", walking_distance_mins:"10", ...std },

  { gharpayy_name:"SNOWY LUXE", area:"Koramangala", locality:"Silk Board, SG Palaya", nearby_landmarks:NL,
    gender:"Co-live", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, gym & games",
    price_double:13000, price_single:23000, ...std },

  // ─── BELLANDUR ──────────────────────────────────────────────────────────
  { gharpayy_name:"KNOX COED", area:"Bellandur", locality:"Kadubeesanahalli", nearby_landmarks:"Sony Software India, Embassy Tech Village",
    google_maps_url:"https://maps.app.goo.gl/adWbc5Z28ixXXGyr7",
    gender:"Co-live", property_type:"Budget",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, mini gym & games",
    price_double:11000, price_single:21000,
    manager_contact:"7337777916", actual_name:"IVA Coliving",
    walking_distance_mins:"5", ...std },

  { gharpayy_name:"BELL COED", area:"Bellandur", locality:"Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/GcoEbrkPuJVseYCC8",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Peak location, newly built with love, pocket friendly",
    price_triple:9000, price_double:13000, price_single:21000,
    manager_contact:"9110664880", owner_contact:"9108895879", actual_name:"Adler Bellandur",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"TREO COED", area:"Bellandur", locality:"Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/98XHhQYXgfkbj1Hd9",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler, food good",
    price_double:12000, price_single:21000,
    owner_contact:"8639188095", actual_name:"Sri Srinivasa Comfort Co-Living",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"PHANTOM COED", area:"Bellandur", locality:"Ecoworld, Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/dNUpaeppQgt3U2jDA",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"New PG, prime location, private TV, food good",
    price_double:15000, price_single:25000,
    manager_contact:"9133743622", actual_name:"Eden Premium Coliving",
    walking_distance_mins:"15", ...std },

  { gharpayy_name:"ZELITE COED", area:"Bellandur", locality:"Ecoworld, Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/eKvChsGkhj81mWV76",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Peak location, newly built, pocket friendly",
    price_double:16000, price_single:28000,
    manager_contact:"7829501828", owner_contact:"8688066287", actual_name:"Jyotis Homestay Studio Rooms",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"ZILLION COED", area:"Bellandur", locality:"Ecoworld, Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/vqxjy8YQzH9H9DAZA",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler, food good",
    price_double:15000, price_single:25000,
    manager_contact:"7996679991", owner_contact:"9739997392", actual_name:"FAB INN by Echo Coliving",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"ETV LUXE COED", area:"Bellandur", locality:"Ecoworld, Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/Dk2HJpnVUsQCeH9N8",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_double:15000, price_single:25000,
    manager_contact:"9739997392", actual_name:"Echo Coliving",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"QUAL GIRLS", area:"Bellandur", locality:"Ecoworld, Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/8rH5MTcVMKWMY2DAA",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"GYM, GAMES, newly built, no curfew",
    price_triple:12000, price_double:15000, price_single:25000,
    actual_name:"Sapthagiri", walking_distance_mins:"40", ...std },

  { gharpayy_name:"ECO COED", area:"Bellandur", locality:"Bellandur", nearby_landmarks:"Bellandur",
    google_maps_url:"https://maps.app.goo.gl/2VRqASzDKvTc8j7S9",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"Peak location, newly built with love, pocket friendly",
    price_triple:9000, price_double:13000, price_single:23000,
    manager_contact:"9501231237", actual_name:"Leo",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"STANNY COED", area:"Bellandur", locality:"Bellandur, HSR", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/2fhoVN2NYcy9jjCH8",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Peak location, newly built with love, pocket friendly",
    price_double:13000, price_single:24000,
    owner_contact:"7204019777", actual_name:"Stanley Coed",
    walking_distance_mins:"15", ...std },

  { gharpayy_name:"GLEN COED", area:"Bellandur", locality:"Bellandur, HSR", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/oHtiM3ofZQiRGnQY6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Peak location, newly built with love, pocket friendly",
    price_double:13000, price_single:23000,
    owner_contact:"7204019777", actual_name:"Haveli Boys",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"BELLA GC FLATS", area:"Bellandur", locality:"Bellandur", nearby_landmarks:BL,
    google_maps_url:"https://maps.app.goo.gl/NFxceVNPZWcbq6NL7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_double:16000, price_single:29000,
    manager_contact:"9845594559", actual_name:"Arcade Inn",
    walking_distance_mins:"15", ...std },

  { gharpayy_name:"LIVIO COED FLATLIKE", area:"Bellandur", locality:"Kadubeesanahalli", nearby_landmarks:"New Horizon College",
    google_maps_url:"https://maps.app.goo.gl/jaqdRWjiy61txVL39",
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Non Veg",
    common_area_features:["Lounge","Pantry","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Flat-like setup, budget friendly, mini games",
    price_double:23000, price_single:26000,
    actual_name:"IRA Coliving", walking_distance_mins:"15", ...std },

  { gharpayy_name:"ELUX COED", area:"Bellandur", locality:"Kadubeesanahalli", nearby_landmarks:"Kadubeesanahalli",
    gender:"Co-live", property_type:"Premium", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good premium vibe", food_type:"Both",
    common_area_features:["Lounge","Gym","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Very luxury property",
    price_double:19000, price_single:28000,
    manager_contact:"7996679993", owner_contact:"9346405038", actual_name:"Infinity Inn Echo",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"PAVION COED", area:"Bellandur", locality:"Sarjapur Bellandur", nearby_landmarks:BL,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Friendly vibe", food_type:"Both",
    common_area_features:["Lounge","Gym","Study Area"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Premium budget property",
    price_double:13000, price_single:23000,
    actual_name:"Eden Premium", walking_distance_mins:"5", ...std },

  { gharpayy_name:"ZONEGL COED", area:"Bellandur", locality:"Near SJR Bellandur", nearby_landmarks:BL,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good friendly vibe", food_type:"Both",
    common_area_features:["Lounge","Study Area"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Near jogger park",
    price_double:14000, price_single:25000,
    manager_contact:"9110719095", actual_name:"Live Loop",
    walking_distance_mins:"5", ...std },

  { gharpayy_name:"SJR AFFO COED", area:"Bellandur", locality:"Sarjapur Bellandur", nearby_landmarks:"Near Wipro, SJR Office",
    google_maps_url:"https://maps.app.goo.gl/vCsVhjBrjCeQMbHS8",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby", food_type:"Both",
    common_area_features:["Lounge","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, close to Wipro", price_double:12000, price_single:21000,
    manager_contact:"8951560310", actual_name:"Cabanan Willow Lux",
    walking_distance_mins:"2", ...std },

  { gharpayy_name:"MYNT COED", area:"Bellandur", locality:"Near Myntra Office", nearby_landmarks:"Myntra Office, Bellandur",
    google_maps_url:"https://maps.app.goo.gl/dZESHUqvxvXkr4a56",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Office area", food_type:"Both",
    common_area_features:["Gym"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Near Myntra office",
    price_double:13000, price_single:24000,
    actual_name:"Urban Coliving", walking_distance_mins:"3", ...std },

  // ─── MAHADEVAPURA ────────────────────────────────────────────────────────
  { gharpayy_name:"ZEAL COED", area:"Mahadevapura", locality:"Bagmane, CV Raman", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/9Qiz9B2S7VzVkagd8",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_double:12000, price_single:22000,
    owner_contact:"7829930666", group_name:"Bliss Group", actual_name:"Bliss Comfort",
    walking_distance_mins:"30", ...std },

  { gharpayy_name:"PRIVE COED", area:"Mahadevapura", locality:"Bagmane, CV Raman", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/V63nDgazKy62DBW98",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_double:15000, price_single:25000,
    actual_name:"Primestay Coliving", walking_distance_mins:"30", ...std },

  { gharpayy_name:"MIVON COED", area:"Mahadevapura", locality:"Bagmane, CV Raman", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/A2gTtGAhC4GfLByK9",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Suite"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_double:16000, price_single:28000,
    manager_contact:"7729858699", group_name:"Urban Coliving", actual_name:"Urban Coliving",
    walking_distance_mins:"30", ...std },

  { gharpayy_name:"BIGBROOK COED", area:"Mahadevapura", locality:"Brookfield, Bagmane", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/1JSY7tnYhzS6TxtU9",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_double:17000, price_single:30000,
    actual_name:"Apex Coliving", walking_distance_mins:"10", ...std },

  { gharpayy_name:"ZEEST COED", area:"Mahadevapura", locality:"Brookfield, Bagmane", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/xpp8Ekvknp7NxdUAA",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_double:14000, price_single:24000,
    manager_contact:"8985878106", actual_name:"WIX Coliving Mahadevapura",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"COOL COED BALCONY", area:"Mahadevapura", locality:"Bagmane, CV Raman", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/qUP1uw7MQ3XaQNiQ6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler, balcony",
    price_double:16000, price_single:26000,
    manager_contact:"8688790159", owner_contact:"8555810106", actual_name:"Qix Coliving",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"ITP COED", area:"Mahadevapura", locality:"Brookfield, ITPL", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/vtfw6ECtQLMcySVTA",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_triple:10000, price_double:13000, price_single:23000,
    manager_contact:"9164515777", actual_name:"AA Premium Coliving",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"ITP ONE COED", area:"Mahadevapura", locality:"Brookfield, ITPL", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/qNX3JZyzkti14X9s5",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_triple:10000, price_double:13000, price_single:23000,
    manager_contact:"9164515777", actual_name:"AA Premium Coliving Block B",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"THUB COED", area:"Mahadevapura", locality:"Brookfield, Bagmane", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/gWyt5JCjXRZed4WY6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_double:13000, price_single:23000,
    manager_contact:"9164203777", actual_name:"Urban Coliving",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"ESTEEM COED", area:"Mahadevapura", locality:"Bagmane, CV Raman", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/XA1cnj8SRYavUjZq7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"New PG, all amenities, premium property",
    price_double:14000, price_single:25000,
    manager_contact:"9912969023", owner_contact:"7204019777", actual_name:"Signature Colive",
    walking_distance_mins:"30", ...std },

  { gharpayy_name:"BGM MAX COED", area:"Mahadevapura", locality:"Bagmane, CV Raman", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/QuLYHW5y9i1yt1qQA",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_double:13000, price_single:23000,
    manager_contact:"7013603027", owner_contact:"7204019777", actual_name:"Mr & Mrs Mahadev",
    walking_distance_mins:"30", ...std },

  { gharpayy_name:"BALC PHIX BGM", area:"Mahadevapura", locality:"Bagmane, CV Raman", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/1etTC7JAqtfc6KKp6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"New property, close to Bagmane Tech Park, balcony rooms",
    price_double:13000, price_single:24000,
    manager_contact:"9959829782", actual_name:"KS Bloom",
    walking_distance_mins:"30", ...std },

  { gharpayy_name:"PHIX BGM COED", area:"Mahadevapura", locality:"Mahadevapura, Bagmane", nearby_landmarks:ECV,
    google_maps_url:"https://maps.app.goo.gl/1etTC7JAqtfc6KKp6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"New property, very close to Bagmane Tech Park, good food",
    price_double:12500, price_single:22000,
    manager_contact:"7730811511", owner_contact:"9663194940", actual_name:"SR Comfort",
    walking_distance_mins:"30", ...std },

  { gharpayy_name:"FINN AFFO COED", area:"Mahadevapura", locality:"Mahadevapura, Marathahalli", nearby_landmarks:"Marathahalli Market, AECS",
    google_maps_url:"https://maps.app.goo.gl/RoBKiSqP2E6fgqZR9",
    gender:"Co-live", property_type:"Budget",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby", food_type:"Both",
    common_area_features:["Lounge","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly",
    price_triple:11500, price_double:16000, price_single:25000,
    actual_name:"SV Classic Coliving", walking_distance_mins:"3", ...std },

  { gharpayy_name:"AUXX COED", area:"Mahadevapura", locality:"Mahadevapura", nearby_landmarks:ECV,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professionals", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Premium luxury stay",
    price_double:21000, price_single:32000,
    group_name:"Gharpayy x FF21", actual_name:"FF21 PMC Mahadevapura",
    walking_distance_mins:"3", ...std },

  // ─── MARATHAHALLI ────────────────────────────────────────────────────────
  { gharpayy_name:"MYSTIC COED", area:"Marathahalli", locality:"AECS, Marathahalli", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/EydKS2YoehU6uhfm7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_double:13000, price_single:24000,
    manager_contact:"8500931018", actual_name:"Flux Coliving",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"ZION LUXE COED", area:"Marathahalli", locality:"AECS, Marathahalli", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/X9FTMTJSxecwgWsG6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Suite"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_double:15000, price_single:27000,
    manager_contact:"7993429799", actual_name:"Orion Coliving",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"GG VISTRA COED", area:"Marathahalli", locality:"AECS, Marathahalli", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/q974a6WWhLeur8Tn9",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_triple:11000, price_double:13000, price_single:20000,
    owner_contact:"9052818503", actual_name:"At Homes",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"KMAHALLI COED", area:"Marathahalli", locality:"AECS, Marathahalli", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/WATeMBV11LFhfcxU6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_triple:10000, price_double:13000, price_single:23000,
    owner_contact:"9353999534", actual_name:"Avalon Luxe",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"SOLARIA COED", area:"Marathahalli", locality:"Whitefield, ITPL, ORR", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/WATeMBV11LFhfcxU6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_triple:10000, price_double:13000, price_single:23000,
    owner_contact:"9606798347", group_name:"GG Klear x Medha Sri", actual_name:"Medha Sri Classic",
    walking_distance_mins:"40", ...std },

  { gharpayy_name:"KLEAR COED", area:"Marathahalli", locality:"AECS, Marathahalli", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/WATeMBV11LFhfcxU6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_triple:10000, price_double:13000, price_single:23000,
    actual_name:"Medha Sri Classic", walking_distance_mins:"40", ...std },

  { gharpayy_name:"KLM COED", area:"Marathahalli", locality:"Marathahalli", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Good location",
    price_double:11000, price_single:20000,
    owner_contact:"9110533155", actual_name:"Chap and Dona",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"MAQ COED", area:"Marathahalli", locality:"Marathahalli", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Good locality",
    price_double:14000, price_single:25000,
    manager_contact:"8309733994", actual_name:"Vow Living",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"AURA COED", area:"Marathahalli", locality:"AECS Layout, Marathahalli", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good friendly area", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Spacious premium property",
    price_double:16000, price_single:31000,
    actual_name:"Zen Co-Living", walking_distance_mins:"5", ...std },

  { gharpayy_name:"MUNE COED", area:"Marathahalli", locality:"Marathahalli, Sarjapur Road", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/oS1iuL4KF4Lt4YQcA",
    gender:"Co-live", property_type:"Budget",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby", food_type:"Both",
    common_area_features:["Lounge","Study Area","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly",
    price_double:13000, price_single:20000,
    manager_contact:"9986866022", actual_name:"Sankalpa Co-live",
    walking_distance_mins:"2", ...std },

  { gharpayy_name:"MAXX COED", area:"Marathahalli", locality:"Thubarahalli", nearby_landmarks:"Thubarahalli",
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Veg",
    meals_per_day:2, food_timings:"Breakfast & Dinner",
    common_area_features:COM, amenities:AMN, safety_features:SAF,
    usp:"Premium luxury property",
    price_double:19000, price_single:22000,
    group_name:"Gharpayy x FF21", actual_name:"FF21 LIT Thubarahalli",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"LEXUS COED", area:"Marathahalli", locality:"Marathahalli", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    meals_per_day:2, food_timings:"As per check-in PDF",
    common_area_features:COM, amenities:AMN, safety_features:SAF,
    usp:"Premium luxury property",
    price_double:19000, price_single:22000,
    group_name:"Gharpayy x FF21", actual_name:"FF21 Pods Marathalli",
    walking_distance_mins:"5", ...std },

  { gharpayy_name:"HOOD COED", area:"Marathahalli", locality:"Kundanhalli", nearby_landmarks:MR,
    google_maps_url:"https://maps.app.goo.gl/EkxZH5JPxmpuZbgs8",
    gender:"Co-live", property_type:"Premium", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area, premium", food_type:"Veg",
    meals_per_day:2, food_timings:"Breakfast & Dinner",
    common_area_features:COM, amenities:AMN, safety_features:SAF,
    usp:"Premium pods and studio rooms",
    price_double:22000, price_single:38000,
    group_name:"Gharpayy x FF21", actual_name:"FF21 KDH",
    walking_distance_mins:"3", ...std },

  { gharpayy_name:"BROOKLUXE COED", area:"Marathahalli", locality:"Brookfield, AECS", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    meals_per_day:3, food_timings:"Breakfast, Lunch, Dinner",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:["CCTV","Security Guard","Biometric Access"],
    usp:"Budget friendly, gym & games",
    price_double:15000, price_single:25000,
    group_name:"AA Sparrow", actual_name:"AA Sparrow",
    walking_distance_mins:"2", ...std },

  { gharpayy_name:"SWIZZ LUXE COED", area:"Marathahalli", locality:"Brookfield, AECS", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"All restaurants nearby", food_type:"Both",
    meals_per_day:3, food_timings:"Breakfast, Lunch, Dinner",
    common_area_features:["Lounge","Gym","Rooftop","PS4 Game Room"], amenities:AMN_PARKING,
    safety_features:["CCTV","Security Guard","Biometric Access"],
    usp:"Wakefit orthopaedic mattresses, premium coliving",
    price_triple:13000, price_double:19000, price_single:30000,
    manager_contact:"7996155599", group_name:"Gharpayy x Astraa", actual_name:"Astra Grande Coliving",
    walking_distance_mins:"2", ...std },

  { gharpayy_name:"ZELUXE COED", area:"Marathahalli", locality:"Brookfield, AECS", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    meals_per_day:3, food_timings:"Breakfast, Lunch, Dinner",
    common_area_features:COM, amenities:AMN, safety_features:SAF,
    usp:"Premium furnished property",
    price_double:18000, price_single:35000,
    actual_name:"VSR Dwell", walking_distance_mins:"3", ...std },

  { gharpayy_name:"AURA COED", area:"Marathahalli", locality:"AECS Layout", nearby_landmarks:MR,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good friendly area", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Spacious premium property",
    price_double:16000, price_single:31000,
    actual_name:"Zen Co-Living 2", walking_distance_mins:"5", ...std },

  // ─── ELECTRONIC CITY ────────────────────────────────────────────────────
  { gharpayy_name:"FLEX COED", area:"Electronic City", locality:"Shanthipura, Electronic City", nearby_landmarks:"Semicon Park, Tech37",
    google_maps_url:"https://maps.app.goo.gl/oQYZPJRAYMoQwhp29",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF_BIO, ...food3,
    usp:"Great property, games, close to offices",
    price_triple:9000, price_double:11000, price_single:17000,
    owner_contact:"9515775563", group_name:"P2 Liv In x Gharpayy", actual_name:"eCity Phase 2 Live In Space",
    accessibility:"Metro, Bus", walking_distance_mins:"15", ...std },

  { gharpayy_name:"POP COED", area:"Electronic City", locality:"Electronic City", nearby_landmarks:"Tech 37, Infosys",
    google_maps_url:"https://maps.app.goo.gl/pwusitauxJDy9NfXA",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Great property, games, close to offices",
    price_double:10000, price_single:16000,
    owner_contact:"9989285854", actual_name:"Leo PG",
    walking_distance_mins:"15", ...std },

  { gharpayy_name:"QUO COED", area:"Electronic City", locality:"Shanthipura, Electronic City", nearby_landmarks:"Semicon Park, Tech37",
    google_maps_url:"https://maps.app.goo.gl/pwusitauxJDy9NfXA",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Great property, games, close to offices",
    price_double:10000, price_single:16000,
    owner_contact:"9989285854", actual_name:"Grand Inn",
    accessibility:"Metro, Bus", walking_distance_mins:"15", ...std },

  // ─── WHITEFIELD ─────────────────────────────────────────────────────────
  { gharpayy_name:"BLISS COED", area:"Whitefield", locality:"Brookfield, AECS, Kundanhalli, ITPL", nearby_landmarks:WF,
    google_maps_url:"https://maps.app.goo.gl/Q45VDHrjtKDtfkR87",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Games, balcony rooms, no curfew",
    price_double:13000, price_single:23000,
    manager_contact:"9964718777", owner_contact:"7204019777", actual_name:"Haveli Coliving",
    accessibility:"Metro, Bus", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"METROFIELD COED", area:"Whitefield", locality:"Hopefarm, ITPL, Whitefield", nearby_landmarks:WF,
    google_maps_url:"https://maps.app.goo.gl/mg2SiKg9ZeoND79v6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Best metro connectivity, flat-type setup with sofa, fridge, TV",
    price_double:15000, price_single:24000,
    manager_contact:"9008122779", actual_name:"Hektor",
    accessibility:"Metro, Bus", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"WHIT COED", area:"Whitefield", locality:"Hopefarm, ITPL, Whitefield", nearby_landmarks:WF,
    google_maps_url:"https://maps.app.goo.gl/gWyt5JCjXRZed4WY6",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Balcony room, budget stay, food included",
    price_double:9000, price_single:17000,
    manager_contact:"8639653441", actual_name:"Oka Colive",
    accessibility:"Metro, Bus", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"ASTOR COED", area:"Whitefield", locality:"Hopefarm, ITPL, Whitefield", nearby_landmarks:WF,
    google_maps_url:"https://maps.app.goo.gl/N5Ry9TEyMeFHptTJ7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Balcony rooms, no curfew",
    price_double:14000, price_single:24000,
    manager_contact:"9880077036", actual_name:"Madhura Co-Living PG",
    accessibility:"Metro, Bus", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"ITP LUXE COED", area:"Whitefield", locality:"Near ITPL", nearby_landmarks:WF,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professionals", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Very premium and furnished",
    price_double:16500, price_single:30000,
    manager_contact:"9008014550", group_name:"Gharpayy x FF21", actual_name:"FF21Z Hub",
    accessibility:"Metro, Bus", walking_distance_mins:"3", ...std },

  { gharpayy_name:"SNOWY LUXE WHITEFIELD", area:"Whitefield", locality:"Brookfield, ITPL", nearby_landmarks:WF,
    gender:"Co-live", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, gym & games",
    price_double:13000, price_single:23000,
    actual_name:"Pro 4 Posh", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"ARK COED", area:"Whitefield", locality:"White Rose Layout", nearby_landmarks:WF,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good premium area", food_type:"Both",
    common_area_features:["Lounge","Pantry","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Affordable property",
    price_double:13000, price_single:23000,
    manager_contact:"8186933794", actual_name:"Arcadian Livinn",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"SF VALLEY COED", area:"Whitefield", locality:"Hopefarm, ITPL, Whitefield", nearby_landmarks:WF,
    google_maps_url:"https://maps.app.goo.gl/4PmE3TkT2BtvkXNx7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    utilities_included:"All Inclusive (GST inclusive, food extra)",
    common_area_features:COM, amenities:AMN, safety_features:SAF,
    meals_per_day:0, food_timings:"Self-Cook",
    usp:"Great property, gym, games",
    price_double:15000, price_single:27000,
    actual_name:"Yello", accessibility:"Metro, Bus", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"ZEETA COED", area:"Whitefield", locality:"Whitefield", nearby_landmarks:WF,
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly property",
    price_double:12000, price_single:21000,
    group_name:"Elite4 x Gharpayy", actual_name:"Elite4",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"MEXA COED", area:"Whitefield", locality:"Naruhalli, Whitefield", nearby_landmarks:WF,
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Friendly vibe", food_type:"Both",
    common_area_features:["Lounge","Study Area","Library"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Near to Naruhalli Metro station",
    price_double:13000, price_single:23000,
    group_name:"Urban Coliving", actual_name:"Urban Coliving",
    accessibility:"Metro, Car Parking, Bike", walking_distance_mins:"5", ...std },

  // ─── NAGAWARA ────────────────────────────────────────────────────────────
  { gharpayy_name:"CIA COED", area:"Nagawara", locality:"Manyata, Nagawara", nearby_landmarks:MTP,
    google_maps_url:"https://maps.app.goo.gl/rgAoSF42L1NFdeGp7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN_PARKING, safety_features:["CCTV","Security Guard","Biometric Access","Fire Extinguisher"],
    ...food2,
    usp:"Good PG, prime location, WFH enabler, food good",
    price_double:13000, price_single:22000,
    manager_contact:"7022568295", owner_contact:"9916669290", group_name:"Gopu x Gharpayy", actual_name:"MG Gopu Homestays G4",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"MAGNUS COED", area:"Nagawara", locality:"Manyata, Nagawara", nearby_landmarks:MTP,
    google_maps_url:"https://maps.app.goo.gl/wVcQBggkCpdj2cMB7",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN, safety_features:SAF, ...food3,
    usp:"New property, no curfew",
    price_triple:11000, price_double:13000, price_single:17000,
    owner_contact:"7997477685", group_name:"Surya Colive x Gharpayy", actual_name:"Magnus Surya Coliving PG",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"WISTA GIRLS C", area:"Nagawara", locality:"Manyata, Nagawara", nearby_landmarks:MTP,
    google_maps_url:"https://maps.app.goo.gl/hMYCpCqMosvzbnrQ9",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"New property, no curfew",
    price_double:12000, price_single:21000,
    manager_contact:"9008801504", group_name:"Gharpayy x Surya Royal", actual_name:"Surya Royal Homes Blossom Girls",
    walking_distance_mins:"10", ...std },

  { gharpayy_name:"MTPLUS COED", area:"Nagawara", locality:"Manyata, Hebbal", nearby_landmarks:MTP,
    google_maps_url:"https://maps.app.goo.gl/1be2s7ViM6Z8NYpp8",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_double:13000, price_single:22000,
    owner_contact:"9620785999", group_name:"Gharpayy x Surya Royal", actual_name:"Surya Royal Homes",
    walking_distance_mins:"30", ...std },

  { gharpayy_name:"MTEK COED", area:"Nagawara", locality:"Manyata, Hebbal", nearby_landmarks:MTP,
    google_maps_url:"https://maps.google.com/?q=13.036693,77.615807",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Great property, newly built, games",
    price_double:11000, price_single:20000,
    owner_contact:"9620785999", group_name:"Gharpayy x Surya Royal", actual_name:"Surya Royal Homes",
    walking_distance_mins:"10", ...std },

  // ─── HSR LAYOUT ────────────────────────────────────────────────────────
  { gharpayy_name:"GG NUOVO BOYS", area:"HSR Layout", locality:"HSR, Silk Board", nearby_landmarks:"HSR Layout",
    google_maps_url:"https://maps.app.goo.gl/jugq8GWawc5cSyVn9",
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_triple:8000, price_double:12000, price_single:21000,
    manager_contact:"9032266177", group_name:"Gharpayy x Gayathri", actual_name:"Gayathri PG",
    walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"HS METRO COED", area:"HSR Layout", locality:"Near Bommanahalli Metro", nearby_landmarks:"HSR Layout Metro Station",
    google_maps_url:"https://maps.app.goo.gl/x5b7KqMMoRACS369A",
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:["Lounge","Gym","Pantry"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Premium property, 3 min from metro",
    price_double:16000, price_single:27000,
    manager_contact:"7899700929", group_name:"Gharpayy x Sivani", actual_name:"Sivani Coliving",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"HS HUGO COED", area:"HSR Layout", locality:"Near Hogasandra Metro", nearby_landmarks:"HSR Layout",
    google_maps_url:"https://maps.app.goo.gl/52tJEDzbfbMvTDLF7",
    gender:"Co-live", property_type:"Premium", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good locality", food_type:"Both",
    common_area_features:["Lounge","Pantry","Study Area","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Premium property",
    price_double:16000, price_single:29000,
    manager_contact:"7899700929", group_name:"Sivani Cherry Blossom", actual_name:"Sivani Cherry Blossom",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"HS EDGE COED", area:"HSR Layout", locality:"HSR Layout Metro Station", nearby_landmarks:"HSR Layout Metro",
    google_maps_url:"https://maps.app.goo.gl/x5b7KqMMoRACS369A",
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area", food_type:"Both",
    common_area_features:["Lounge","Study Area"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Premium property, metro access",
    price_double:13000, price_single:21000,
    manager_contact:"7899700929", group_name:"Gharpayy x Sivani", actual_name:"Sivani Living (Iris House)",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"HS AFFO COED", area:"HSR Layout", locality:"HSR Layout, Kudulu", nearby_landmarks:"HSR Layout",
    google_maps_url:"https://maps.app.goo.gl/SHyAe6cYg1a2jZbu9",
    gender:"Co-live", property_type:"Budget",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good locality", food_type:"Both",
    common_area_features:["Lounge","Study Area","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly",
    price_double:13000, price_single:20000,
    actual_name:"Nesto Aloha Coliving PG",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"5", ...std },

  { gharpayy_name:"HS ARQ COED", area:"HSR Layout", locality:"HSR Layout", nearby_landmarks:"Near to Main Road",
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area, near bakery", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Good furnished property",
    price_double:15000, price_single:28000,
    manager_contact:"8978142139", actual_name:"Pro Coed Tripathi Reddy",
    walking_distance_mins:"3", ...std },

  // ─── JP NAGAR / JAYANAGAR / MG ROAD ────────────────────────────────────
  { gharpayy_name:"LUNA GIRLS", area:"Jayanagar", locality:"Jayanagar", nearby_landmarks:"Jayanagar",
    google_maps_url:"https://maps.app.goo.gl/x7frvw1knt4JgM4y9",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Great property, close to offices",
    price_triple:16000, price_double:19000, price_single:31000,
    manager_contact:"7416687752", owner_contact:"7411911136", actual_name:"Sakshi Living Ladies PG",
    accessibility:"Metro", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"VELUXE COED", area:"JP Nagar", locality:"NS Palya, near Vega City Mall", nearby_landmarks:"Vega City Mall",
    google_maps_url:"https://maps.app.goo.gl/LGZV2Wd7mDqvqqPe6",
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Premium locality", food_type:"Both",
    common_area_features:["Lounge","Gym","Pantry","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Premium locality, near Vega City Mall",
    price_double:17000, price_single:29000,
    manager_contact:"7899700929", group_name:"Gharpayy x Sivani", actual_name:"Sivani Living (Lotus)",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"VEGAS COED", area:"JP Nagar", locality:"NS Palya, near Vega City Mall", nearby_landmarks:"Vega City Mall",
    google_maps_url:"https://maps.app.goo.gl/Cv2rVP3zUx3BBq7NA",
    gender:"Co-live", property_type:"Premium",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Premium locality", food_type:"Both",
    common_area_features:["Lounge","Gym","Pantry","Study Area"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Premium locality, daily cleaning",
    price_double:15000, price_single:27000,
    manager_contact:"7899700929", group_name:"Gharpayy x Sivani", actual_name:"Orchid House Vegas Coed",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"VELVET GIRLS", area:"MG Road", locality:"Vasanth Nagar, MG Road", nearby_landmarks:"MG Road",
    google_maps_url:"https://maps.app.goo.gl/ad1JHPLHtfBxF2Q78",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Budget friendly, games, coliving",
    price_triple:10000, price_double:14000, price_single:24000,
    owner_contact:"8088303270", group_name:"Gharpayy Hive Living", actual_name:"Hive Living",
    accessibility:"Metro, Bus", walking_distance_mins:"near MG Road Metro", ...std },

  { gharpayy_name:"QUEEN'S MCC GIRLS", area:"Vasanth Nagar", locality:"Vasanth Nagar, MG Road", nearby_landmarks:"MG Road",
    google_maps_url:"https://maps.app.goo.gl/3e2CEGKgS7ZRpMLV8",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Veg",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food4,
    usp:"New built, premium property",
    price_triple:14000, price_double:19000, price_single:0,
    manager_contact:"6363901319", owner_contact:"9108895879", actual_name:"Adler Stays Vasanth Nagar",
    accessibility:"Metro, Bus", walking_distance_mins:"near MG Road Metro", ...std },

  // ─── BTM LAYOUT / SILK BOARD ─────────────────────────────────────────────
  { gharpayy_name:"STM COED", area:"BTM Layout", locality:"Silk Board, BTM", nearby_landmarks:"Near Metro",
    google_maps_url:"https://maps.app.goo.gl/fMvhD5Sd3ayi4F47A",
    gender:"Co-live", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Great property, close to offices",
    price_double:13000, price_single:23000,
    manager_contact:"8187010212", actual_name:"SLC Royal Co-Live",
    accessibility:"Metro, Bus", walking_distance_mins:"near landmark", ...std },

  { gharpayy_name:"SILQ COED", area:"BTM Layout", locality:"Madiwala, Tavrekere, SG Palya", nearby_landmarks:"Silk Board",
    google_maps_url:"https://maps.app.goo.gl/fLtsUSb7aUkWA2pz8",
    gender:"Co-live", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM_STUDY, amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly, gym & games",
    price_double:13000, price_single:22000,
    actual_name:"Royal White House Coliving", walking_distance_mins:"nearby", ...std },

  { gharpayy_name:"LUKAS COED", area:"BTM Layout", locality:"BTM Layout, Silk Board", nearby_landmarks:"Near Silk Board Metro",
    google_maps_url:"https://maps.app.goo.gl/fLtsUSb7aUkWA2pz8",
    gender:"Co-live", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Good area near to main road", food_type:"Both",
    common_area_features:["Lounge","Study Area","Rooftop"], amenities:AMN, safety_features:SAF, ...food3,
    usp:"Extremely budget friendly",
    price_double:12000, price_single:22000,
    manager_contact:"7893037059", actual_name:"Royal Suit House",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  { gharpayy_name:"FABLE GIRLS", area:"BTM Layout", locality:"Silk Board, near Metro", nearby_landmarks:"Near Silk Board Metro",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing","Triple Sharing"],
    surrounding_vibe:"Friendly vibe", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Good furnished property",
    price_triple:10000, price_double:15000, price_single:26000,
    manager_contact:"8431426795", owner_contact:"9980889487", actual_name:"GMB Comforts",
    accessibility:"Metro, Bus, Bike", walking_distance_mins:"3", ...std },

  // ─── SG PALYA ────────────────────────────────────────────────────────────
  { gharpayy_name:"GG BUBBLO GIRLS SG", area:"Koramangala", locality:"SG Palya, Tavrekere", nearby_landmarks:NL,
    google_maps_url:"https://maps.app.goo.gl/Rdo9UCsirJ3ZcPRKA",
    gender:"Girls", property_type:"Mid", noise_level:"Low",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"All restaurants nearby", food_type:"Both",
    common_area_features:COM, amenities:AMN_PARKING, safety_features:SAF, ...food3,
    usp:"Budget friendly, gym & games",
    price_double:13000, price_single:21000,
    actual_name:"Gayathri PG SG", walking_distance_mins:"10", ...std },

  // ─── INDIRANAGAR / DOMLUR ──────────────────────────────────────────────
  { gharpayy_name:"DOM GIRLS", area:"Indiranagar", locality:"Domlur, Indiranagar", nearby_landmarks:"Near Indiranagar",
    google_maps_url:"https://maps.app.goo.gl/ubgUxqMaBY6vFqa66",
    gender:"Girls", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food3,
    usp:"Newest PG, prime location, WFH enabler",
    price_double:12000, price_single:21000,
    actual_name:"Arcade Inn",
    accessibility:"Metro, Bus", walking_distance_mins:"near Indiranagar Metro", ...std },

  // ─── YESHWANTHPUR ──────────────────────────────────────────────────────
  { gharpayy_name:"FORT BOYS", area:"Yeshwanthpur", locality:"Christ Yeshwanthpur Campus", nearby_landmarks:"Christ University Yeshwanthpur",
    google_maps_url:"https://maps.app.goo.gl/2i8xYsTyaY2NEJNe9",
    gender:"Boys", property_type:"Mid",
    room_types:["Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"450m from Christ Yeshwanthpur, budget friendly",
    price_double:17000,
    actual_name:"Puzzles Bravado",
    accessibility:"Metro, Bus", walking_distance_mins:"15", ...std },

  { gharpayy_name:"PARADISE GIRLS", area:"Yeshwanthpur", locality:"Christ Yeshwanthpur Campus", nearby_landmarks:"Christ University Yeshwanthpur",
    google_maps_url:"https://maps.app.goo.gl/2i8xYsTyaY2NEJNe9",
    gender:"Girls", property_type:"Mid",
    room_types:["Double Sharing","Triple Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"350m from Christ Yeshwanthpur campus",
    price_triple:17000, price_double:20000,
    manager_contact:"9686025547", actual_name:"Best Girls ADL",
    accessibility:"Metro, Bus", walking_distance_mins:"15", ...std },

  { gharpayy_name:"WISE BOYS", area:"Yeshwanthpur", locality:"Christ Yeshwanthpur Campus", nearby_landmarks:"Christ University Yeshwanthpur",
    google_maps_url:"https://maps.app.goo.gl/2i8xYsTyaY2NEJNe9",
    gender:"Boys", property_type:"Mid",
    room_types:["Single Sharing","Double Sharing"],
    surrounding_vibe:"Working professional and posh crowd", food_type:"Both",
    common_area_features:COM, amenities:AMN, safety_features:SAF, ...food4,
    usp:"750m from Christ Yeshwanthpur campus",
    price_double:14000, price_single:23000,
    manager_contact:"8217863474", actual_name:"900 Mtr Adler Boys",
    accessibility:"Metro, Bus", walking_distance_mins:"15", ...std },
];

// ─── Run seed ──────────────────────────────────────────────────────────────
async function seed() {
  console.log(`\n🌱 Seeding ${pgs.length} PGs into Supabase…\n`);

  // Wipe existing data
  const { error: delErr } = await supabase.from("pg_properties").delete().neq("id","00000000-0000-0000-0000-000000000000");
  if (delErr) console.warn("⚠️  Could not wipe table:", delErr.message);

  let ok = 0, fail = 0;
  for (const pg of pgs) {
    const { error } = await supabase.from("pg_properties").insert(pg);
    if (error) { console.error(`❌  ${pg.gharpayy_name}:`, error.message); fail++; }
    else { console.log(`✅  ${pg.gharpayy_name}`); ok++; }
  }
  console.log(`\n✅ Seeded ${ok} / ${pgs.length} PGs  |  ${fail} failed\n`);
}

seed().catch(console.error);
